name: sgwest
favicon: null
layout_spectrum: 0.0040305983275175095
typography_spectrum: 0.74149264767766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9863984805997461
  lightness: 0.800549847073853
  saturation: 0.9554480931255966
  rhythmicContrast: 0.8816129709593952
purpose: []
